#include <iterator>
#include <memory>

#include "Game.h"

std::shared_ptr<GameUpdate> GameHandler::process_disconnect(ClientDisconnectedUpdate& event) {
    int disconnected_id = event.get_id();
    if (this->curr_pl->first == disconnected_id) {
        auto nx_pl = std::next(this->curr_pl);
        if (nx_pl == this->players.end()) {
            nx_pl = this->players.begin();
        }
        // since player is no longer in the game, "server" sends this update
        this->eventq.push(std::make_shared<ClientPTurnAdvanceUpdate>(SERVER_ID, nx_pl));
    }
    this->players.erase(disconnected_id);
    plcount--;

    std::cout << "A player disconnected. Now online: " << plcount << " players." << std::endl;
    return std::make_shared<GamePlayerDisconnectedUpdate>(disconnected_id);
}

std::shared_ptr<GameUpdate> GameHandler::process_new_connect(ClientConnectedUpdate& event) {
    plcount++;
    std::cout << "New player connected. Now online: " << plcount << " players." << std::endl;

    // makes new player the current player if lobby is empty
    if (this->curr_pl == this->players.end()) {
        this->curr_pl = this->players.find(event.get_id());

        // event is generated by "server" since lobby is empty
        this->eventq.push(std::make_shared<ClientPTurnAdvanceUpdate>(SERVER_ID, this->curr_pl));
    }

    return std::make_shared<GamePlayerConnectedUpdate>(event.get_id());
}

std::shared_ptr<GameUpdate> GameHandler::process_message(ClientMessageUpdate& event) {
    return std::make_shared<GameChatMessageUpdate>(event.get_id(), event.get_msg());
}

std::shared_ptr<GameUpdate> GameHandler::process_NullUpdate(ClientNullUpdate& event) {
    return std::make_shared<GameNullUpdate>();
}

std::shared_ptr<GameUpdate> GameHandler::process_TurnAdvance(ClientPTurnAdvanceUpdate& event) {
    auto new_curr_pl = event.get_new_pl();

    if (new_curr_pl == this->players.end()) {
        return std::make_shared<GameNullUpdate>();
    }
    this->curr_pl = new_curr_pl;
    return std::make_shared<GameTurnChangeUpdate>(new_curr_pl->first);
}

std::shared_ptr<GameUpdate> GameHandler::process_box2d(ClientBox2DUpdate& event) {
    return std::shared_ptr<GameUpdate>(box2d.process(event));
}
