bazooka:
  damage: 50
  radius: 2
  ammount_of_bullets: -1
  ammount_of_fragments: -1
  radius_of_fragments: -1
  damage_of_fragments: -1
  restitution: 0
  wind: true
  timer: false
mortar:
  damage: 50
  radius: 2
  ammount_of_bullets: 10
  ammount_of_fragments: 6
  radius_of_fragments: 2
  damage_of_fragments: 10
  restitution: 0
  wind: true
  timer: false
banana:
  damage: 70
  radius: 4
  ammount_of_bullets: 5
  ammount_of_fragments: -1
  radius_of_fragments: -1
  damage_of_fragments: -1
  restitution: 0.6
  wind: false
  timer: true
red_grenade:
  damage: 30
  radius: 2
  ammount_of_bullets: 10
  ammount_of_fragments: 6
  radius_of_fragments: 2
  damage_of_fragments: 10
  restitution: 0.6
  wind: false
  timer: true
green_grenade:
  damage: 30
  radius: 2
  ammount_of_bullets: -1
  ammount_of_fragments: -1
  radius_of_fragments: -1
  damage_of_fragments: -1
  restitution: 0.6
  wind: false
  timer: true
holy_grenade:
  damage: 110
  radius: 8
  ammount_of_bullets: 2
  ammount_of_fragments: -1
  radius_of_fragments: -1
  damage_of_fragments: -1
  restitution: 0.6
  wind: false
  timer: true
air_strike:
  damage: 40
  radius: 2
  ammount_of_bullets: 2
  ammount_of_fragments: 6
  radius_of_fragments: 2
  damage_of_fragments: 40
  restitution: 0
  wind: true
  timer: false
baseball:
  damage: 10
  radius: 0.5
  ammount_of_bullets: -1
  ammount_of_fragments: -1
  radius_of_fragments: -1
  damage_of_fragments: -1
  restitution: 0
  wind: false
  timer: false
dynamite:
  damage: 50
  radius: 4
  ammount_of_bullets: 5
  ammount_of_fragments: -1
  radius_of_fragments: -1
  damage_of_fragments: -1
  restitution: 0
  wind: false
  timer: true
